openapi: 3.0.3
info:
  title: User API
  description: API for managing users
  version: 0.0.1
servers:
  - url: '{host}/api'
    variables:
      host:
        default: http://localhost:8080
paths:
  /users/v1:
    get:
      summary: Get all users
      description: Retrieve a list of all users
      responses:
        '200':
          description: A list of all users
          parameters:
            - in: query
              required: false
              name: directory
              schema:
                $ref: '#/components/schemas/directory'
              description: Filter users by directory
            - in: query
              required: false
              name: task
              schema:
                $ref: '#/components/schemas/task'
              description: Filter users by task
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
        '400':
          $ref: '#/components/responses/badRequest'
    post:
      summary: Create a new user
      description: Add a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
  /users/v1/{id}:
    get:
      summary: Get a user by ID
      description: Retrieve a specific user by its ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        '400':
          $ref: '#/components/responses/badRequest'
    put:
      summary: Update a user
      description: Update the details of an existing user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        '400':
          $ref: '#/components/responses/badRequest'
    delete:
      summary: Delete a user
      description: Remove a user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: User deleted successfully
        '400':
          $ref: '#/components/responses/badRequest'
components:
  schemas:
    user:
      id:
        type: string
      name:
        type: string
      email:
        type: string
      createdDate:
        type: string
        format: date-time
      updatedDate:
        type: string
        format: date-time
  responses:
    badRequest:
      description: Bad request
      content:
        application/json:
          schema:
            type: object